// SPDX-License-Identifier: MIT

#ifndef _VESC_DATA_H_
#define _VESC_DATA_H_

#include <stdint.h>
#include "vesc.h"

typedef enum
{
	VESC_COMM_FW_VERSION = 0,
	VESC_COMM_JUMP_TO_BOOTLOADER,
	VESC_COMM_ERASE_NEW_APP,
	VESC_COMM_WRITE_NEW_APP_DATA,
	VESC_COMM_GET_VALUES,
	VESC_COMM_SET_DUTY,
	VESC_COMM_SET_CURRENT,
	VESC_COMM_SET_CURRENT_BRAKE,
	VESC_COMM_SET_RPM,
	VESC_COMM_SET_POS,
	VESC_COMM_SET_DETECT,
	VESC_COMM_SET_SERVO_POS,
	VESC_COMM_SET_MCCONF,
	VESC_COMM_GET_MCCONF,
	VESC_COMM_GET_MCCONF_DEFAULT,
	VESC_COMM_SET_APPCONF,
	VESC_COMM_GET_APPCONF,
	VESC_COMM_GET_APPCONF_DEFAULT,
	VESC_COMM_SAMPLE_PRINT,
	VESC_COMM_TERMINAL_CMD,
	VESC_COMM_PRINT,
	VESC_COMM_ROTOR_POSITION,
	VESC_COMM_EXPERIMENT_SAMPLE,
	VESC_COMM_DETECT_MOTOR_PARAM,
	VESC_COMM_DETECT_MOTOR_R_L,
	VESC_COMM_DETECT_MOTOR_FLUX_LINKAGE,
	VESC_COMM_DETECT_ENCODER,
	VESC_COMM_DETECT_HALL_FOC,
	VESC_COMM_REBOOT,
	VESC_COMM_ALIVE,
	VESC_COMM_GET_DECODED_PPM,
	VESC_COMM_GET_DECODED_ADC,
	VESC_COMM_GET_DECODED_CHUK,
	VESC_COMM_FORWARD_CAN,
	VESC_COMM_SET_CHUCK_DATA,
	VESC_COMM_CUSTOM_APP_DATA,
	VESC_COMM_NON
} VESC_FW23_3_COMM_PACKET_ID;

#endif /* _VESC_DATA_H_ */